language: cpp
sudo: required
dist: xenial

compiler:
    - gcc
    - clang

env:
    - CXXFLAGS=-std=c++14
    - CXXFLAGS=-std=c++14 CMAKE_BUILD_TYPE=Debug
    - CXXFLAGS=-std=c++14 CMAKE_BUILD_TYPE=Release

script:
    - mkdir build.tmp && cd build.tmp
    - cmake ..
    - make
    - make check

