language: cpp
sudo: required
dist: trusty

compiler:
    - gcc
    - clang

install:
    # Get newer compilers
    - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main" > clang.list
    - sudo mv clang.list /etc/apt/sources.list.d/
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y --force-yes g++-6 clang-4.0 lldb-4.0 lld-4.0
    - 'if [ "$CXX" = "g++" ]; then echo "using gcc : 6 : g++-6 ;" > ~/user-config.jam; fi'
    - 'if [ "$CXX" = "clang++" ]; then echo "using clang : 4 : clang++-4.0 ;" > ~/user-config.jam; fi'
    - g++-6 --version
    - clang++-4.0 --version

script:
    - ./runtests $CXX
