language: cpp
sudo: required
dist: xenial

notifications:
    webhooks:
        urls:
            # Telegram
            - "https://fathomless-fjord-24024.herokuapp.com/notify"
        on_success: always
        on_failure: always
        on_start: never

compiler:
    - gcc
    - clang

env:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

install:
    - sudo apt-get install ninja-build

script:
    - mkdir build.tmp && cd build.tmp
    - cmake .. -G Ninja
    - ninja
    - ninja check

