#!/usr/bin/env python3
import os
from os import path
from shlex import quote
import subprocess
import sys


def worked(execute, expected=0):
    print(' '.join([quote(c) for c in execute]))
    code = subprocess.call(execute)
    if not (code == expected):
        sys.exit(code)


COMPILER = {
    'clang++': ['-Wno-unused-const-variable'],
    'clang++-3.8': ['-Wno-unused-const-variable'],
    'clang++-4.0': ['-Wno-unused-const-variable'],
}
def compile(command, expected=0, fn=None):
    for compiler in sys.argv[1:] or ['clang++', 'g++']:
        execute = [compiler] + command + COMPILER.get(compiler, [])
        worked(execute, expected)
        if fn: fn()


CPP_OPTS = ['-Iinclude', '-Werror', '-Wall', '-Wextra', '-Wpedantic']

if __name__ == "__main__":
    print("Testing Cord...")

    for std in ['-std=c++14', '-std=c++1z']:
        folder = 'test/compile'
        for fname in os.listdir(folder):
            execute = CPP_OPTS + [std] + ['-fsyntax-only', path.join(folder, fname)]
            compile(execute)

        folder = 'test/run'
        for fname in os.listdir(folder):
            execute = CPP_OPTS + [std] + ['-o', '/tmp/a.out', path.join(folder, fname)]
            compile(execute, fn=lambda: worked(['/tmp/a.out']))
