version: 2
jobs:
  build:
    docker:
      - image: ubuntu:focal

    environment:
      CC: gcc-10
      CXX: g++-10

    steps:
      - checkout

      - run:
          name: install
          environment:
            DEBIAN_FRONTEND: noninteractive
          command: |
            apt-get update
            apt-get install -y build-essential cmake $CC libssl-dev ninja-build
            ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
            dpkg-reconfigure --frontend noninteractive tzdata

      - run:
          name: cmake
          command: |
            mkdir build.tmp
            cd build.tmp
            cp ../.travis.CMakeLists.txt CMakeLists.txt
            cmake . -G Ninja

      - run:
          name: ninja
          command: ninja -C build.tmp
      - run:
          name: check tests
          command: ninja -C build.tmp check
